### PR TITLE
Inital bindat integration

### PR DESCRIPTION
**Pull request by Inc0n**
The incoming data the netrepl sends to its client (our emacs buffer here) receives a byte string similar to this format.

```
<header1><result of evaluation, warning, error message etc><header2><netrepl prompt string>
```

This should provide a good platform for tweaking it further.

Good thing is inital bindat integrations works, and it would reduce LoC.

Here is the bad things, this would only cover for  the protocol that goes through `branch 6. Otherwise`, to handle the other case which is `If (= (msg 0) 0xFF)` [1].

However, it no new features are to be introduced, this solution should suffice.

[1] [the netrepl protocol comments](https://github.com/janet-lang/spork/blob/df6623355cebfd3841084b965c690b251426637c/spork/netrepl.janet#L35-L56).

### CODE REVIEW

**Comment by sogaiu** [comment]
## Trial Results of the PR

I tried the PR.  I've summarized some of what I observed below.

### Connection Related Results

The following is what I saw in `*Messages*` after `M-x ajsc`:

```
Connecting to REPL on 'localhost:9365'...
received: "\0\0\0localhost:9365_00006p:1: "
error in process filter: if: Args out of range: "\0\0\0localhost:9365_00006p:1: ", 29
error in process filter: Args out of range: "\0\0\0localhost:9365_00006p:1: ", 29
```

This is reproducible for me across fresh Emacs instances.

I think this may only happen when the connection is established though.

### Post-Connection Basic Expression Evaluation Results

Subsequent to the connection, if I go ahead and type an expression like `(+ 1 1)` followed by the Enter key into the `*ajsc-repl*` buffer, I do see evaluation results followed by a new prompt (yay!).

The situation on first connect is slightly different from all subsequent interactions IIUC.  I think the post-connection (well, after receiving the first prompt) interactions all have evaluation results and the very first response after connecting only has a prompt.

If that description is accurate, perhaps the difference hasn't been accounted for in the current code.

### Post-Connection Other Expression Evaluation Results

When I tried sending some other expressions, I sometimes got output like:

```
error in process filter: Args out of range: ...
```

That didn't just happen using the "Send ..." commands from ajsc -- I also tried pasting directly into the `*ajsc-repl*` buffer and could see the results there too.

I'm not sure why that is just yet.  Perhaps it's related to what I've written in the next section.

FWIW, the code I was testing with sending is basically stuff from [here](https://github.com/sogaiu/a-janet-spork-client/blob/8932cf87b40862b8abb2640289326debe89316ce/ajsc/last-expression.janet).

The large `(def expr-grammar ...)` form consistently caused the "error in process filter..." messages for me.  The initial `(import ./delims)` form would sometimes and not other times.

## Observations about the PR Code

That sounds good if it (or something similar) is working for you.  I also appreciate less lines of code, and possibly bindat itself may be better tested for doing the sorts of things we're interested in here.

I do have a concern that the PR code as it stands doesn't appear to account for the bit from the docs about:

>       The output to the filter may come in chunks of any size. A
>       program that produces the same output twice in a row may
>       send it as one batch of 200 characters one time, and five
>       batches of 40 characters the next. If the filter looks for
>       certain text strings in the subprocess output, make sure to
>       handle the case where one of these strings is split across
>       two or more batches of output;

It would be great if this didn't happen but at least at some point I suspect this sort of thing did occur in Emacs.  

Put in terms of `ajsc.el`, I don't think there is a guarantee that `ajsc--parse-in-bytes*` will get called with exactly the appropriate number of bytes that will work for unpacking.  Possibly sometimes `in-bytes` would not have enough bytes for unpacking to succeed and sometimes it might have too many bytes (so the left-over bytes would just be lost if not saved somewhere).

One idea is to just ignore it for now and try to do something about it if it ever occurred.  It's possible that the odd behavior I was observing with the "error in process filter..." is related to this chunking but that's currently speculation.

### Minor Point About the Netrepl Protocol Comment

Regarding the link in the first post to the netrepl protocol comment (https://github.com/janet-lang/spork/blob/df6623355cebfd3841084b965c690b251426637c/spork/netrepl.janet#L35-L56), to clarify, I believe that's to an older version of the text [1].  It's somewhat different from the [version available currently](https://github.com/janet-lang/spork/blob/48aa9f9b04e2fc0848a7834d6957db3328c0440e/spork/netrepl.janet#L37-L70).  I haven't understood in enough detail how they differ so may be it's not relevant.  Still, perhaps it's better to be looking at the most recent version -- although some effort seems to go into backward-compatibility, I think things do change sometimes in Janetland that don't remain working with older ways.

---

[1] I posted 2 links earlier -- sorry if that was not so clear before.

**Comment by Inc0n** [comment]
First, thanks for the feedbacks :) They are very detailed as always. 

Here are my understanding to the issues and concerns you raised.

## error in process filter: Args out of range: ...

This is most likely a results of using bindat for the fixed format, whilst the incoming data sometimes have varying format.

The coded bindat spec expects two message always, one of them the repl prompt and the other the result of evalution from the expression sent.

And the other most likely cause is the chunk issue you have informed me about. Where the data is not sent in one go, and the current bindat just expects everything in one string.

## Solution

The solution is to use bindat differently, i.e. just use it for encode and decode, `ajsc-net-header-str` and `ajsc-decode-net-header-str` respectively.

Which I will demonstrate in my next few commits.

**Comment by Inc0n** [comment]
Ok, I got there in the end, I accidentally commited my work on bindat packing. Which is not part of the solution originally.

Essentially now we just use bindat to pack and unpack the messages for us. And that is it. The original parsing is fine, since that would take care of the chunk right.

So after using bindat, I think there won't be much benefits in performance, and the original code all work out as well.

If you would like to consider about performance more, it would be comment out all the `message`s, or make them debug log (i.e. control with a verbose level flag).

And a few minor changes in the parsing which could help.

But I think this should be nearing the end of the bindat saga.

**Comment by sogaiu** [comment]
Thanks for the explanations and further work.

Please find below a few points.

### Some Minor Tweaks

I made a few minor tweaks to get it to work here:
```diff
$ git diff
diff --git a/ajsc.el b/ajsc.el
index 01eda7e..76cd322 100644
--- a/ajsc.el
+++ b/ajsc.el
@@ -392,7 +392,7 @@ be sending anything remotely close to the limit."
           (let* ((string* (substring-no-properties string))
                  (msg (ajsc-pack-string string*)))
             (message "sending: %S" msg)
-            (process-send-string process msg)
+            (process-send-string proc msg)
             ;; (comint-simple-send proc msg)
             )))
   (setq mode-line-process '(":%s")))
@@ -472,7 +472,7 @@ endpoint.  ENDPOINT is a string of the form: \"hostname:port\"."
               ;; XXX: without this, header bytes were being interpreted as
               ;;      multibyte sometimes
               (set-process-coding-system repl-process 'binary)
-              (process-send-string process (ajsc-pack-string endpoint))
+              (process-send-string repl-process (ajsc-pack-string endpoint))
               (with-current-buffer repl-buffer
                 (ajsc-mode)
                 (pop-to-buffer (current-buffer))
```

With those changes, the code seems to be working and I'm no longer seeing the process filter related error messages.

One odd thing I noticed is that if I try to use `ajsc-send-region` when the region is for a symbol or keyword, although the `*ajsc-repl*` buffer displays the content from the region, I don't see an evaluation result.  Subsequent evaluation attempts don't all work either.

Continuing to try a variety of additional evaluations can lead to eventually there being an evaluation result, but it looks like may be the multiple evaluation attempt content wasn't sent each time as the results I get back look like they are for strings that have been concatenated.  For example, `peg/match` Enter, followed by `1` Enter at some point yielded `compile error: unknown symbol peg/match1`.

I'm not sure yet what the issue is so I'll investigate further -- FWIW, I checked with the master branch and I didn't reproduce there.

### Logging and Performance

> If you would like to consider about performance more, it would be comment out all the messages, or make them debug log (i.e. control with a verbose level flag).

Yeah, I found waiting for the logging output to be a bit much :)

I did that in [this commit](https://github.com/sogaiu/a-janet-spork-client/commit/f6cad9d7f9713fc04cffbd846cd26b6f366d5ab5) the other day -- though that's on a different branch.  That looks close to what you had in mind, right?

> And a few minor changes in the parsing which could help.

I'm happy to hear about specific things if you had some in mind.  Even if we don't touch on them at this stage, perhaps having a record of them would be useful for later revisitation.

### To Use or Not To Use

> So after using bindat, I think there won't be much benefits in performance, and the original code all work out as well.

Ok.

Do you think the code is more readable with the bindat changes?

As long as bindat functions well, I think there is more clarity, though I suppose that's more likely true for people who have a fairly decent understanding of bindat :)

**Comment by Inc0n** [comment]
## Some Minor Tweaks

> I made a few minor tweaks to get it to work here:

Oops, I left some errors slipped in like that again. I was being lazy as `(require 'smartparens)` was constantly frowning at me on buffer evaluation. I just need to make the `thingatpt` changes but not stage theses commits.

Okay, I applied you patch manually at "type fix" 70763355e4e60c12d69ef6f8dad8e85838fad0c4 comiit.

> One odd thing I noticed is that...

The `ajsc-send-region` with keyword and symbols I couldn't re-produce. It may be related to this problem which I fix in "at repl prompt fix" https://github.com/sogaiu/a-janet-spork-client/pull/2/commits/9d4490f8c24267757544e24db772ce5e5a94ba7c commit. Also it may be helpful to kill the `*ajsc-repl*` buffer or run M-x `ajsc-mode` again on the repl buffer.

## Logging and Performance

> I did that in [this commit](https://github.com/sogaiu/a-janet-spork-client/commit/f6cad9d7f9713fc04cffbd846cd26b6f366d5ab5) the other day -- though that's on a different branch. That looks close to what you had in mind, right?

That looks good to me 👍.

> I'm happy to hear about specific things if you had some in mind. 

Please have a look at this: parse bytes commit 97d3aed56fb105fc9ca26b85599991fa5246be86 in a different branch, and I would like to hear your thoughts on this, but to summarize the most notable difference:

1. we can use keep track of less states (i.e. uses less `defvar`s)
2. similar to 1. it helps that we can return the partial messages earlier, which means there are less stuff to keep track of.

## To Use or Not To Use

> though I suppose that's more likely true for people who have a fairly decent understanding of bindat :)

Haha, that is fairly true. It is clearer to me, but of course I had my fair share of poking at it.

I am definitely more inclined to get it merged into master, and that would be my first contribution to the project (shiny contributor flag XD).

But if you do decide to get `bindat` merged, please consider [simple-bindat](https://github.com/Inc0n/a-janet-spork-client/tree/simple-bindat) instead. It's just one commit, nothing else is changed unnecessarily, unlike here.

P.S. Hmm my headlines seems not to be rendering Idk why

**Comment by sogaiu** [comment]
Thanks for the updates and parse bytes commit.

### Regarding the Parse Bytes Commit

I had a look and tried the code out.  I appreciate less state and It seems to work pretty well :+1: 

I am curious whether it could ever happen that there aren't enough bytes for  complete information for a length.  That might not be a problem if enough bytes come along subsequently, but for the cases of the very first message and possibly for when not enough bytes are provided by Emacs (even for non-first messages), I'm not seeing clearly how the current code would handle it.  May be those things will never happen :)

### Possible Ways Forward

I've put a variety of things in a branch at [this commit](https://github.com/sogaiu/a-janet-spork-client/commit/d04843e7b7b30e9a799d4367b083f743bb72b0da).

This includes:

* bindat [1] (the ajsc-pack-string bits)
* parse-in-bytes improvements
* thingatpt use instead of smartparens
* putting additional debug-related message calls in and placing those and previous relevant ones behind a flag
* some other minor things

If this works for you, I can put this on the master branch -- though if you want to explicitly show up in the commit log, I'm happy to do it another way as well.

I'm also ok to go the simple-bindat route initially, though I'm not sure how to merge that code, so if you prefer that, may be you could make a PR?

I can subsequently add additional bits such as the debugging-related output changes and thingatpt use.

I think having a commit that uses thingatpt would be good even though it doesn't seem to handle Janet arrays or tables.  If that bothers anyone enough I have the Janet code for expression detection that I can add later.

---

[1] Oh, I forgot to mention that it looks like `uintr` might be [deprecated from Emacs 29](https://github.com/emacs-mirror/emacs/blob/6b9f9df9454a59b74790c402916df8628bb9d477/lisp/emacs-lisp/bindat.el#L955-L957).  May be something to attend to later.

**Comment by Inc0n** [comment]
> I am curious whether it could ever happen that there aren't enough bytes for complete information for a length.

yeap it would not handle situation for broken message. I.e. if someone's internet got unplugged in the middle of the client receiving the message from server. 

The state of `ajsc--decoded-len` would be left with the unfinished data from previous communication.

## simple bindat 

I see that simple-bindat was just merged, what's left for discussion would be IMO:
- parse-in-bytes improvements
  I see you are happy consider the points I raised with my implementation, which I am happy for it to be merged. It's the concern you raise about half way interrupted communication, you are happy to leave things be for now? I mean we could put a timer or keep timestamp, so the broken communication can be resetted. More visibly, an interactive function for explicity reset could be also introduced (i.e. set `ajsc--decoded-len` to `nil`).
  So we could put this on hold for now?
- thingatpt
  Good news is that it seems `thingatpt` may be extensible [lisp/thingatpt.el#L310](https://github.com/emacs-mirror/emacs/blob/6b9f9df9454a59b74790c402916df8628bb9d477/lisp/thingatpt.el#L310.)
  Here is a less intrusive way to define new things, see comment [lisp/thingatpt.el#L58](https://github.com/emacs-mirror/emacs/blob/6b9f9df9454a59b74790c402916df8628bb9d477/lisp/thingatpt.el#L58)
  Personally I am not a fan of calling external processes to find the bounds, so I can't say that is an improvements over installing an extra dependency.
  And it seems that we could take advantage of the syntax parser [janet-mode.el#L201](https://github.com/ALSchwalm/janet-mode/blob/master/janet-mode.el#L201), [janet-mode.el#L231](https://github.com/ALSchwalm/janet-mode/blob/master/janet-mode.el#L231).

> [1] Oh, I forgot to mention that it looks like uintr might be [deprecated from Emacs 29](https://github.com/emacs-mirror/emacs/blob/6b9f9df9454a59b74790c402916df8628bb9d477/lisp/emacs-lisp/bindat.el#L955-L957). May be something to attend to later.

I will get to that by the latest when emacs 29 is official released and on brew :)

> I can subsequently add additional bits

That should sum up the things up to this point, I will leave the rest of them at your discretion then.

**Comment by sogaiu** [comment]
### Re: parse-in-bytes improvements

We could put your code into place and try it out for a while (or I guess you could be running a customized version :) ).  If you find it to be lacking we can try to address the situation in some fashion.  In practice, I'm not sure how frequent the interrupted communication scenario would be and it's unclear to me what one would want as a way to recover -- may be just resetting like you suggest would be fine.  Perhaps actual usage experience would better inform what to do if anything.

On a side note, may be you know this already, but FWIW there is [client-side code for netrepl in `spork/netrepl.janet`](https://github.com/janet-lang/spork/blob/48aa9f9b04e2fc0848a7834d6957db3328c0440e/spork/netrepl.janet#L328-L352) -- not sure if that could be that helpful, but another path would be to talk to a local janet process that does the networking for us.  I don't know if that would be an overall win though.

### Re: thingatpt

Thanks for the bits about extension.  I had no idea.  Sounds promising!

I am not so keen on using janet-mode's parsing as there is [an outstanding issue about long-strings](https://github.com/ALSchwalm/janet-mode/issues/9) that a few people have tried to fix [1](https://github.com/ALSchwalm/janet-mode/pull/11) [2](https://github.com/ALSchwalm/janet-mode/pull/12) unsuccessfully [1].  (On the whole I like janet-mode's quality and simplicity, but I don't think it's being attended to so much these days.)

Still, if it (or some of the bits it contains) work(s) well enough for the task at hand, that would be good.

If a Emacs-29+ (not too far off?) solution is (eventually?) acceptable and you don't mind using tree-sitter, another option for recognizing things might be to use tree-sitter's parsing capabilities.

Although, to get this working, even with Emacs 29, one needs a shared library for a tree-sitter grammar for Janet.  It's not calling an external process but may be it would count as an additional dependency and it's a bit more fuss to get into place than some Emacs Lisp thing.

An "out-of-the-box-works-with-Emacs" solution would be nice.  I'm fine to put some effort toward seeing what can be done.

---

[1] I think I managed to address most of the issues in janet-ts-mode, but there may still be a few related things lurking.  To get an idea of the sorts of constructs that janet-mode doesn't handle so well (perhaps particularly apparent when using rainbow-delimiters), please see these files: https://github.com/sogaiu/janet-ts-mode/tree/master/rainbow-delimiters-test-samples

**Comment by Inc0n** [comment]
> FWIW there is [client-side code for netrepl in spork/netrepl.janet](https://github.com/janet-lang/spork/blob/48aa9f9b04e2fc0848a7834d6957db3328c0440e/spork/netrepl.janet#L328-L352)

Ah I played with client netrepl before, it works fine in the terminal, but I couldn't get it to interact (function as repl) as a comint buffer. I ran it like `janet -e "(import spork/netrepl) (netrepl/client %S %s)"`.

> not sure if that could be that helpful, but another path would be to talk to a local janet process that does the networking for us

I think free network handling is definitely a plus. The first obstacle comes to my mind is sorting out how to make it function in a comint buffer (if you managed to do this, I'd apprieciate if you show me how it's done).

That can also be useful for inf-janet and netrepl integration, though I don't know how far you would like to go down this rabbit hole ;)

> interrupted communication

Again, janet netrepl client could be a good way for solving this.

### Re: Re: thingatpt

> Although, to get this working, even with Emacs 29, one needs a shared library for a tree-sitter grammar for Janet. It's not calling an external process but may be it would count as an additional dependency and it's a bit more fuss to get into place than some Emacs Lisp thing.

I am on board with tree-sitter. Thanks for the consideration :)

> Still, if it (or some of the bits it contains) work(s) well enough for the task at hand, that would be good.

I think if the expression is a long string expression aka string enclosed with ticks (\`) then it will most likely send the wrong region. But if these more "difficult" expressions are enclosed within more "normal" expression this could work. This would requires a bit more fiddling. I would rather wait for Emacs29+TS to come and save us with grace.

**Comment by sogaiu** [comment]
Thanks for your thoughts.  Just have a brief comment.

> sorting out how to make it function in a comint buffer

May be I'll look into this a bit.  Likely next week at the earliest though.

**Comment by Inc0n** [comment]
Please do 👍

**Comment by sogaiu** [comment]
@Inc0n Had a few moments to make [an attempt](https://github.com/sogaiu/snr).

It's basically ajrepl that's been renamed plus one `.janet` file.

The key piece is `netrepl-proxy.janet`.  I took the guts of `spork/netrepl`'s [`client`](https://github.com/janet-lang/spork/blob/48aa9f9b04e2fc0848a7834d6957db3328c0440e/spork/netrepl.janet#L328-L352) and carved away some bits.

Assuming there's an appropriate netrepl server running locally on the usual port number, `M-x snr` in a buffer with Janet code should bring up a repl buffer.  There's no prompt, but expression evaluation seems to work.

I don't really know why the netrepl client code doesn't work as-is.  May be I can look into details later.

Likely a better thing can be made using `ev`, but that's for another day or may be even another person :)

**Pull request closed without merging**
